#!/bin/bash

# Get the directory of the script (covers edge cases)
# Handle edge cases without subprocesses
if [[ "${BASH_SOURCE[0]}" = /* ]]; then
    # Absolute path
    SCRIPT_DIR="${BASH_SOURCE[0]%/*}"
elif [[ "${BASH_SOURCE[0]}" == */* ]]; then
    # Relative path with directory component
    SCRIPT_DIR="$PWD/${BASH_SOURCE[0]%/*}"
else
    # Just a filename
    SCRIPT_DIR="$PWD"
fi

. $SCRIPT_DIR/tools/shell.sh

# Return to where we were executed from upon death
START_DIR=$PWD
set_death_dir $START_DIR

say "BUILD: GoLib"
say "BEGIN"

# Do all our work from the location of this script
pushd $SCRIPT_DIR > /dev/null

# If the module is not even initialized, start there
if [ ! -f go.mod ]; then
	modname=${PWD##*/}
	say "Initializing Modle: $modname"
	go mod init $modname
	go mod tidy
	go mod vendor
fi

# Iterate over output of `go mod tidy` which recommends things that we should go get... and go get them!
gobin=`which go`
while read cmd
do
	# If `go mod tidy` turns up nothing, it may be an empty string, so just skip it
	if [[ -n "$cmd" && "${cmd//[[:space:]]}" ]]; then
		echo "cmd: $gobin $cmd"
		`$gobin $cmd`
	fi
done <<< `go mod tidy 2>&1 |grep "found" | sed -e 's/go: found /get /g' | sed -e 's/ in .*$//g'`

# Return to where we began
popd > /dev/null
say "\nDONE! :^D"
