#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

. $SCRIPT_DIR/tools/shell.sh

# Return to where we were executed from upon death
START_DIR=`pwd`
set_death_dir $START_DIR

say "BUILD: GoLib"
say "BEGIN"

if [ ! -f go.mod ]; then
	say "Initializing"
	go mod init
fi

cd $START_DIR
say "\nDONE! :^D"

