#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

. $SCRIPT_DIR/tools/shell.sh

# Return to where we were executed from upon death
START_DIR=`pwd`
set_death_dir $START_DIR

say "BEGIN"

# Lint all source files first
PASS=1
#for f in `find . -name "*.go"`; do
for f in `find . -type f -name '*.go' | sed -r 's|/[^/]+$||' |sort |uniq`; do
	go vet $f
	if [ $? != 0 ]; then
		PASS=0
	fi
done
if [ $PASS == 0 ]; then
	die "FAILED Vetting stage!"
fi


# Now run unit tests
for testrunner in `find $SCRIPT_DIR -name "t"`; do
	echo "Running test: '$testrunner'"
	/bin/bash $testrunner
done

cd $START_DIR
say "\nDONE! :^D"

