#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

. $SCRIPT_DIR/Testing/shell.sh

# Return to where we were executed from upon death
START_DIR=`pwd`
set_death_dir $START_DIR

say "BEGIN"

for testrunner in `find $SCRIPT_DIR -name "t"`; do
	echo "Running test: '$testrunner'"
	/bin/bash $testrunner
done

cd $START_DIR
say "\nDONE! :^D"

