#!/bin/bash

TESTRUNNER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. $TESTRUNNER_DIR/../Testing/shell.sh

say "BEGIN: $TESTRUNNER_DIR"
cd $TESTRUNNER_DIR

say "\n >> timesource_test.go"
go test -count=1 timesource_test.go timesource.go timestamp.go
die_on_error $? "ERROR!"

say "\n >> timestamp_test.go"
go test -count=1 timestamp_test.go timesource.go timestamp.go
die_on_error $? "ERROR!"

say "\nDONE: $TESTRUNNER_DIR"

