#!/bin/bash

TESTRUNNER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
. $TESTRUNNER_DIR/../tools/shell.sh

say "BEGIN: $TESTRUNNER_DIR"
cd $TESTRUNNER_DIR

say "\n >> cacheitem_test.go"
go test -v -count=1 cacheitem_test.go cacheitem.go
die_on_error $? "ERROR!"

say "\n >> cache_test.go"
go test -v -count=1 cache_test.go cache.go cacheitem.go
die_on_error $? "ERROR!"

say "\nDONE: $TESTRUNNER_DIR"

