#!/bin/bash

. ../Testing/shell.sh

cwd=`pwd`
say "BEGIN: $cwd"

say "\n >> cacheitem_test.go"
go test -count=1 cacheitem_test.go cacheitem.go
die_on_error $? "ERROR!"

say "\n >> cache_test.go"
go test -count=1 cache_test.go cache.go cacheitem.go
die_on_error $? "ERROR!"

say "\nDONE: $cwd"

